### ISSUE TITLE
depend on SDWebImage 3.7.5 

### ISSUE THREAD

**Issue by CoderYuChong** [litt1e-p/LPCarouselView#1]
The latest version 3.8.1

**Comment by litt1e-p** [comment]
so you look forward to new version 3.8+? I will update it later, thanks for issue

**Comment by CoderYuChong** [comment]
YES, and ‘LPPhotoViewer’ , thank you

**Comment by litt1e-p** [comment]
OK

**Comment by CoderYuChong** [comment]
SDWebImage 4.0.0 you can depend on，thank you

**Comment by litt1e-p** [comment]
@CoderYuChong OK
